
var date_ver='2010/01/25 15:17';var Prototype={Version:'1.4.0_pre10_ajax',emptyFunction:function(){},K:function(x){return x}};var Class={create:function(){return function(){this.initialize.apply(this,arguments);}}};var Abstract=new Object();Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.inspect=function(object){try{if(object==undefined)return'undefined';if(object==null)return'null';return object.inspect?object.inspect():object.toString();}catch(e){if(e instanceof RangeError)return'...';throw e;}};Function.prototype.bind=function(object){var __method=this;return function(){return __method.apply(object,arguments);};};Function.prototype.bindAsEventListener=function(object){var __method=this;return function(event){return __method.call(object,event||window.event);};};Object.extend(Number.prototype,{toColorPart:function(){var digits=this.toString(16);if(this<16)return'0'+digits;return digits;},succ:function(){return this+1;},times:function(iterator){$R(0,this,true).each(iterator);return this;}});var Try={these:function(){var returnValue;for(var i=0;i<arguments.length;i++){var lambda=arguments[i];try{returnValue=lambda();break;}catch(e){}}
return returnValue;}};var PeriodicalExecuter=Class.create();PeriodicalExecuter.prototype={initialize:function(callback,frequency){this.callback=callback;this.frequency=frequency;this.currentlyExecuting=false;this.registerCallback();},registerCallback:function(){setInterval(this.onTimerEvent.bind(this),this.frequency*1000);},onTimerEvent:function(){if(!this.currentlyExecuting){try{this.currentlyExecuting=true;this.callback();}finally{this.currentlyExecuting=false;}}}};function $(){var elements=new Array();for(var i=0;i<arguments.length;i++){var element=arguments[i];if(typeof element=='string')
element=document.getElementById(element);if(arguments.length==1)
return element;elements.push(element);}
return elements;};var Ajax={getTransport:function(){return Try.these(function(){return new ActiveXObject('Msxml2.XMLHTTP')},function(){return new ActiveXObject('Microsoft.XMLHTTP')},function(){return new XMLHttpRequest()})||false;}};Ajax.Base=function(){};Ajax.Base.prototype={setOptions:function(options){this.options={method:'post',asynchronous:true,parameters:''};Object.extend(this.options,options||{});},responseIsSuccess:function(){return this.transport.status==undefined||this.transport.status==0||(this.transport.status>=200&&this.transport.status<300);},responseIsFailure:function(){return!this.responseIsSuccess();}};Ajax.Request=Class.create();Ajax.Request.Events=['Uninitialized','Loading','Loaded','Interactive','Complete'];Ajax.Request.prototype=Object.extend(new Ajax.Base(),{initialize:function(url,options){this.transport=Ajax.getTransport();this.setOptions(options);this.request(url);},request:function(url){var parameters=this.options.parameters||'';if(parameters.length>0)parameters+='&_=';try{if(this.options.method=='get')
url+='?'+parameters;this.transport.open(this.options.method,url,this.options.asynchronous);if(this.options.asynchronous){this.transport.onreadystatechange=this.onStateChange.bind(this);setTimeout((function(){this.respondToReadyState(1)}).bind(this),10);}
this.setRequestHeaders();var body=this.options.postBody?this.options.postBody:parameters;this.transport.send(this.options.method=='post'?body:null);}catch(e){};},setRequestHeaders:function(){var requestHeaders=[];if(this.options.method=='post'){requestHeaders.push('Content-type','application/x-www-form-urlencoded');if(this.transport.overrideMimeType)requestHeaders.push('Connection','close');}
if(this.options.requestHeaders)
requestHeaders.push.apply(requestHeaders,this.options.requestHeaders);for(var i=0;i<requestHeaders.length;i+=2)
this.transport.setRequestHeader(requestHeaders[i],requestHeaders[i+1]);},onStateChange:function(){var readyState=this.transport.readyState;if(readyState!=1)
this.respondToReadyState(this.transport.readyState);},evalJSON:function(){try{var json=this.transport.getResponseHeader('X-JSON'),object;object=eval(json);return object;}catch(e){}},respondToReadyState:function(readyState){var event=Ajax.Request.Events[readyState];var transport=this.transport,json=this.evalJSON();if(event=='Complete')
(this.options['on'+this.transport.status]||this.options['on'+(this.responseIsSuccess()?'Success':'Failure')]||Prototype.emptyFunction)(transport,json);(this.options['on'+event]||Prototype.emptyFunction)(transport,json);if(event=='Complete')
this.transport.onreadystatechange=Prototype.emptyFunction;}});Ajax.Updater=Class.create();Ajax.Updater.ScriptFragment='(?:<script.*?>)((\n|.)*?)(?:<\/script>)';Object.extend(Object.extend(Ajax.Updater.prototype,Ajax.Request.prototype),{initialize:function(container,url,options){this.containers={success:container.success?$(container.success):$(container),failure:container.failure?$(container.failure):(container.success?null:$(container))};this.transport=Ajax.getTransport();this.setOptions(options);var onComplete=this.options.onComplete||Prototype.emptyFunction;this.options.onComplete=(function(transport,object){this.updateContent();onComplete(transport,object);}).bind(this);this.request(url);},updateContent:function(){var receiver=this.responseIsSuccess()?this.containers.success:this.containers.failure;var match=new RegExp(Ajax.Updater.ScriptFragment,'img');var response=this.transport.responseText.replace(match,'');var scripts=this.transport.responseText.match(match);if(receiver){if(this.options.insertion){new this.options.insertion(receiver,response);}else{receiver.innerHTML=response;}}
if(this.responseIsSuccess()){if(this.onComplete)
setTimeout(this.onComplete.bind(this),10);}
if(this.options.evalScripts&&scripts){match=new RegExp(Ajax.Updater.ScriptFragment,'im');setTimeout((function(){for(var i=0;i<scripts.length;i++)
eval(scripts[i].match(match)[1]);}).bind(this),10);}}});Ajax.PeriodicalUpdater=Class.create();Ajax.PeriodicalUpdater.prototype=Object.extend(new Ajax.Base(),{initialize:function(container,url,options){this.setOptions(options);this.onComplete=this.options.onComplete;this.frequency=(this.options.frequency||2);this.decay=1;this.updater={};this.container=container;this.url=url;this.start();},start:function(){this.options.onComplete=this.updateComplete.bind(this);this.onTimerEvent();},stop:function(){this.updater.onComplete=undefined;clearTimeout(this.timer);(this.onComplete||Ajax.emptyFunction).apply(this,arguments);},updateComplete:function(request){if(this.options.decay){this.decay=(request.responseText==this.lastText?this.decay*this.options.decay:1);this.lastText=request.responseText;}
this.timer=setTimeout(this.onTimerEvent.bind(this),this.decay*this.frequency*1000);},onTimerEvent:function(){this.updater=new Ajax.Updater(this.container,this.url,this.options);}});function in_array(needle,haystack){for(var i=0;i<haystack.length;i++){if(haystack[i]==needle){return true;}}
return false;}
var tooltip=function(){var top=3;var left=11;var maxw=670;var speed=5;var timer=10;var endalpha=95;var alpha=0;var accept_fade=0;var tt,t,c,b,h;var ie=document.all?true:false;return{show:function(v,w,ntt){ntt=ntt||'';tt=$(ntt+'tt');c=$(ntt+'ttcont');b=$('ttbot');t=$('tttop');if(tt){if(accept_fade){tt.style.opacity=0;tt.style.filter='alpha(opacity=0)';}
document.onmousemove=this.pos;tt.style.display='block';c.innerHTML=v;tt.style.width=w?w+'px':'auto';if(!w&&ie){if(t)t.style.display='none';if(b)b.style.display='none';tt.style.width=tt.offsetWidth;if(t)t.style.display='block';if(b)b.style.display='block';}
if(tt.offsetWidth>maxw){tt.style.width=maxw+'px'}
h=parseInt(tt.offsetHeight)+top;if(accept_fade){clearInterval(tt.timer);tt.timer=setInterval(function(){tooltip.fade(1)},timer);}}},pos:function(e){var u=ie?event.clientY+document.documentElement.scrollTop:e.pageY;var l=ie?event.clientX+document.documentElement.scrollLeft:e.pageX;var scrolledX,scrolledY;if(window.pageYOffset){scrolledX=window.pageXOffset;scrolledY=window.pageYOffset;}
else if(document.documentElement&&document.documentElement.scrollTop){scrolledX=document.documentElement.scrollLeft;scrolledY=document.documentElement.scrollTop;}
else if(document.body){scrolledX=document.body.scrollLeft;scrolledY=document.body.scrollTop;}
tt.style.top=(((u-scrolledY-h)>0)?((u-h)+'px'):(u+'px'));tt.style.left=(l+left)+'px';},fade:function(d){var a=alpha;if((a!=endalpha&&d==1)||(a!=0&&d==-1)){var i=speed;if(endalpha-a<speed&&d==1){i=endalpha-a;}else if(alpha<speed&&d==-1){i=a;}
alpha=a+(i*d);tt.style.opacity=alpha*.01;tt.style.filter='alpha(opacity='+alpha+')';}else{clearInterval(tt.timer);if(d==-1){tt.style.display='none'}}},hide:function(){document.onmousemove=null;if(accept_fade){clearInterval(tt.timer);tt.timer=setInterval(function(){tooltip.fade(-1)},timer);}else if(tt){tt.style.display='none';}}};}();function BulleWrite(txt_,e_,x_,y_){tooltip.show(txt_);}
function BulleHide(){tooltip.hide();}
function BulleWriten(txt_,e_,x_,y_){tooltip.show(txt_,false,'n');}
function insertText(formName,txtToAdd){var txtObj=$(formName);if(navigator.appName=="Microsoft Internet Explorer")
{var str=document.selection.createRange().text;txtObj.focus();var sel=document.selection.createRange();sel.text=str+txtToAdd;return;}
else
{oldPos=txtObj.scrollTop;oldHght=txtObj.scrollHeight;pos=txtObj.selectionEnd+txtToAdd.length;txtObj.value=txtObj.value.substr(0,txtObj.selectionStart)+
txtObj.value.substr(txtObj.selectionStart,txtObj.selectionEnd-txtObj.selectionStart)+
txtToAdd+txtObj.value.substr(txtObj.selectionEnd);txtObj.selectionStart=pos;txtObj.selectionEnd=pos;newHght=txtObj.scrollHeight-oldHght;txtObj.scrollTop=oldPos+newHght;}
txtObj.focus();};var sas_tmstp=Math.round(Math.random()*10000000000);var sas_masterflag=1;function SmartAdServer(sas_pageid,sas_formatid,sas_target){if(sas_masterflag==1){sas_masterflag=0;sas_master='M';}
else{sas_master='S';}
document.write('<scr'+'ipt ID="SmartScr'+sas_formatid+'" SRC="http://www3.smartadserver.com/call/pubj/'+sas_pageid+'/'+sas_formatid+'/'+sas_master+'/'+sas_tmstp+'/'+escape(sas_target)+'?"></scr'+'ipt>');};var adOnTop=1;var scriptStrip=0;var adBottom=null;ccm_universe='www.commentcamarche.net';function su_ad(sg){magiclink.add(sg);};magiclink={lastpos:0,processed_keywords:[],spaces_counter:0,processed_input_strings:[],num_btns_in_ul:2,gs:function(){var textarea=$('message');if(typeof textarea.selectionStart!='undefined')
return textarea.selectionStart;textarea.focus();var range=textarea.createTextRange();range.moveToBookmark(document.selection.createRange().getBookmark());range.moveEnd('character',textarea.value.length);return(textarea.value.length-range.text.length);},cm:function(m){var output='';for(i=0;i<m.length;i++){output+='*';}
return output;},mask:function(txt){txt=txt.replace(/\[.*?\]/g,magiclink.cm);txt=txt.replace(/[.a-zA-Z0-9_+-]+@[.a-zA-Z0-9-]{2,}[.][a-zA-Z]{2,}/g,magiclink.cm);txt=txt.replace(/\s*[=]+[^=\r\n]+[=]+/g,magiclink.cm);txt=txt.replace(/http:\/\/\S+[\w#!:.?+=&%@!\-\/]*/g,magiclink.cm);txt=txt.replace(/\<conf\>.*?\<\/conf\>/g,magiclink.cm);return txt;},cancel:function(id){magiclink.processed_keywords.push(id);idstring='suggest'+id;$(idstring).parentNode.removeChild($(idstring));if($('suggest_ph').getElementsByTagName('li').length<=magiclink.num_btns_in_ul){if($('apply_all')){$('apply_all').style.display='none';}
if($('cancel_all')){$('cancel_all').style.display='none';}}
return false;},apply:function(id,txt,url){magiclink.processed_keywords.push(id);var textarea=$('message');var oldPos=textarea.scrollTop;var idstring='suggest'+id;var dummy=magiclink.mask(textarea.value);var reg=new RegExp("\\b"+re_esc(txt)+"\\b");var s_p=dummy.search(reg);if(s_p>=0){e_p=s_p+txt.length;textarea.value=textarea.value.substr(0,s_p)+'['+url+' '+txt+']'+textarea.value.substr(e_p);}
$(idstring).parentNode.removeChild($(idstring));textarea.scrollTop=oldPos;if($('suggest_ph').getElementsByTagName('li').length<=magiclink.num_btns_in_ul){if($('apply_all')){$('apply_all').style.display='none';}
if($('cancel_all')){$('cancel_all').style.display='none';}}
return false;},action_all:function(is_apply){var prefix=(is_apply)?'apply':'cancel';var fils=$('suggest_ph').childNodes;var nbFils=fils.length;var reg=new RegExp('[0-9]+');var id=0;var filsArray=[];for(var i=0;i<nbFils;i++){id=0;if(fils[i].nodeName.toLowerCase()=='li'){if(fils[i].id!='apply_all'&&fils[i].id!='cancel_all'){id=reg.exec(fils[i].id);if(id!=0){filsArray.push(id);}}}}
for(i=0;i<filsArray.length;i++){$(prefix+filsArray[i]).onclick();}
$('apply_all').style.display='none';$('cancel_all').style.display='none';},apply_all:function(){magiclink.action_all(true);},cancel_all:function(){magiclink.action_all(false);},add:function(su){if(su.length){for(i=0;i<su.length;i++){id=su[i][0];tx=su[i][1];ur=su[i][2];if(!in_array(id,magiclink.processed_keywords)){if(!$('suggest'+id)&&suggest_this_url!=ur){li=document.createElement('li');li.id='suggest'+id;li.innerHTML='<input type="hidden" name="suggest['+id+']" value="'+ht_en(tx)+'" /><input type="hidden" name="suggest_url['+id+']" value="'+ht_en(ur)+'" /><a href="'+ur+'" target="_blank">'+tx+'</a><a href="#" class="apply" id="apply'+id+'" onclick="return magiclink.apply('+id+',\''+ad_sl(tx)+'\',\''+ur+'\');"></a><a href="#" class="cancel" id="cancel'+id+'" onclick="return magiclink.cancel('+id+');"></a>';$('suggest_ph').appendChild(li);if($('apply_all')){$('apply_all').style.display='block';}
if($('cancel_all')){$('cancel_all').style.display='';}}}}}},dorequest:function(ccm_c_p){var textarea=$('message');var text=textarea.value;if(text.charCodeAt(ccm_c_p)==10||text.charCodeAt(ccm_c_p)==13){ccm_c_p=ccm_c_p-1;}
var p_lb=text.lastIndexOf("\n",ccm_c_p);if(p_lb<0){p_lb=text.lastIndexOf("\r",ccm_c_p);}
if(p_lb<0){text=text;}
else{text=text.substring(p_lb+1);}
var n_lb=text.indexOf("\n");if(n_lb<0){n_lb=text.indexOf("\r");}
var l_l='';if(n_lb<0){l_l=text.replace(/[-\s]+$/g,'');}
else{l_l=text.substring(0,n_lb).replace(/[-\s]+$/g,'');}
if(l_l.length>=2){var escaped_string=escape(magiclink.mask(l_l).replace(/[*]+/g,'*'));if(!in_array(escaped_string,magiclink.processed_input_strings)){magiclink.processed_input_strings.push(escaped_string);var u_s='http://suggest.commentcamarche.net/kw?q='+escaped_string+'&u='+ccm_universe;var headTag=document.getElementsByTagName('head')[0];if($('magiclinkScript')){headTag.removeChild($('magiclinkScript'));}
script=document.createElement('script');script.id='magiclinkScript';script.type='text/javascript';script.src=''+u_s;headTag.appendChild(script);}}},on_click:function(){magiclink.dorequest(magiclink.gs());},on_keyup:function(e){var key=(window.event)?window.event.keyCode:e.which;if(key==13||key==10){magiclink.dorequest(magiclink.gs()-1);}
else if(key==32){magiclink.spaces_counter++;if(magiclink.spaces_counter==10){magiclink.spaces_counter=0;magiclink.dorequest(magiclink.gs());}}}}
function re_esc(s){return s.replace(/([.*+?^${}()|[\]\/\\])/g,'\\$1')};function ad_sl(str){return(str+'').replace(/([\\"'])/g,"\\$1").replace(/\u0000/g,"\\0");};function ht_en(wText){if(typeof(wText)!="string"){wText=wText.toString();};wText=wText.replace(/&/g,"&amp;");wText=wText.replace(/"/g,"&quot;");wText=wText.replace(/</g,"&lt;");wText=wText.replace(/>/g,"&gt;");wText=wText.replace(/'/g,"&#146;");return wText;};function insertTag(txtName,tag,enclose,skip_tag,force_text){skip_tag=skip_tag||false;force_text=force_text||false;var closeTag,Tag;if(skip_tag){closeTag='';Tag=tag;}else{closeTag=((enclose)?"</"+tag+">":"");Tag="<"+tag+">";}
var txtObj=$(txtName);if(navigator.appName=="Microsoft Internet Explorer")
{var str=(force_text)?force_text:document.selection.createRange().text;txtObj.focus();var sel=document.selection.createRange();sel.text=Tag+str+closeTag;return;}
else
{oldPos=txtObj.scrollTop;oldHght=txtObj.scrollHeight;str=(force_text)?force_text:txtObj.value.substr(txtObj.selectionStart,txtObj.selectionEnd-txtObj.selectionStart);pos=txtObj.selectionEnd+Tag.length+closeTag.length+((force_text)?str.length:0);txtObj.value=txtObj.value.substr(0,txtObj.selectionStart)+Tag+
str+
closeTag+txtObj.value.substr(txtObj.selectionEnd);txtObj.selectionStart=pos;txtObj.selectionEnd=pos;newHght=txtObj.scrollHeight-oldHght;txtObj.scrollTop=oldPos+newHght;}
txtObj.focus();};function PutThat(url){window.open(url,"_blank","location=yes,toolbar=yes,directories=yes,status=yes, menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes");};function GetParam(name){var match=new RegExp(name+"=(.+)[&]","i").exec(location.search);if(match==null){match=new RegExp(name+"=(.+)","i").exec(location.search);}
if(match==null){return null;}
match=match+"";result=match.split(",");return result[1];};ref_k='';function refk(){var ptn=/google[.]/i;var q='';if(ref_k){q=ref_k;}
else{if(ptn.exec(document.referrer)!=null){var u_p=document.referrer.split('?');if(u_p[1]){var u_a=u_p[1].split('&');for(var i=0;i<u_a.length;i++){var kv=u_a[i].split('=');if(kv[0]=='q'){q=decodeURIComponent(kv[1]).replace(/(allinanchor|allintext|allintitle|allinurl|author|cache|define|filetype|group|id|inanchor|info|insubject|intext|intitle|inurl|location|phonebook|related|rphonebook|site|source)[:][^ +]+/,'');q=q.replace(/[+]/g,' ');}}}}
ref_k=q;}
return q;};function strip_accents(str){var s=str;var rExps=[/[\xC0-\xC2]/g,/[\xE0-\xE2]/g,/[\xC8-\xCA]/g,/[\xE8-\xEB]/g,/[\xCC-\xCE]/g,/[\xEC-\xEE]/g,/[\xD2-\xD4]/g,/[\xF2-\xF4]/g,/[\xD9-\xDB]/g,/[\xF9-\xFB]/g];var repChar=['A','a','E','e','I','i','O','o','U','u'];for(var i=0;i<rExps.length;i++)
s=s.replace(rExps[i],repChar[i]);return s;};function compareStringLengths(a,b){if(a.length<b.length)
return 1;if(a.length>b.length)
return-1;return 0;};function h_j(te,container){var gtc='#000000';var glc=new Array('#ffff66','#a0ffff','#99ff99','#ff9999','#ff66ff');var reg=new RegExp("[-:;,+=(){}/?<>!*'\\\"\\[\\]\\ ]+","g");var words=strip_accents(te).toLowerCase().split(reg);words.sort(compareStringLengths);if(words.length>0){var c=0;for(var i=0;i<words.length;i++){if(words[i].length>2&&container){h_g(words[i],container,glc[c]);c=(c==glc.length-1)?0:c+1;}}}}
function h_g(te,container,color){var t_l=te.toLowerCase();for(var i=0;i<container.childNodes.length;i++){var node=container.childNodes[i];if(node.nodeType==3){var data=node.data;var d_l=strip_accents(data.toLowerCase());if(d_l.indexOf(t_l)!=-1){var n_n=document.createElement('span');node.parentNode.replaceChild(n_n,node);var res;while((res=d_l.indexOf(t_l))!=-1){n_n.appendChild(document.createTextNode(data.substr(0,res)));n_n.appendChild(c_n_g(document.createTextNode(data.substr(res,te.length)),color));data=data.substr(res+te.length);d_l=d_l.substr(res+te.length);}
n_n.appendChild(document.createTextNode(data));}}
else{h_g(te,node,color);}}};function c_n_g(child,color){var node=document.createElement('span');node.style.fontWeight='bold';node.appendChild(child);return node;};var ccm_language='fr';function google_ad_request_done(google_ads){var s='';var i;var google_ad_title='Google Ads';switch(ccm_language){case'fr':google_ad_title='Annonces Google';break;case'en':google_ad_title='Google Ads';break;case'es':google_ad_title='Anuncios Google';break;case'pt':google_ad_title='Anúncios Google';break;case'it':google_ad_title='Annunci Google';break;case'de':google_ad_title='Google-Anzeigen';break;}
if(google_ads.length==0){return;}
if(google_ads[0].type=="flash"){s+='<a href=\"'+
google_info.feedback_url+'\" class="adsense_ad" target="_blank">'+google_ad_title+'</a><br/><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+' codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" WIDTH="'+
google_ad.image_width+'" HEIGHT="'+
google_ad.image_height+'"> <PARAM NAME="movie" VALUE="'+
google_ad.image_url+'">'+'<PARAM NAME="quality" VALUE="high">'+'<PARAM NAME="AllowScriptAccess" VALUE="never">'+'<EMBED src="'+
google_ad.image_url+'" WIDTH="'+
google_ad.image_width+'" HEIGHT="'+
google_ad.image_height+'" TYPE="application/x-shockwave-flash"'+' AllowScriptAccess="never" '+' PLUGINSPAGE="http://www.macromedia.com/go/getflashplayer"></EMBED></OBJECT>';}else if(google_ads[0].type=="image"){s+='<a href=\"'+
google_info.feedback_url+'\" class="adsense_ad" target="_blank">'+google_ad_title+'</a><br/><a href="'+
google_ads[0].url+'" target="_top" title="afficher la page '+
google_ads[0].visible_url+'" onmouseout="window.status=\'\'" onmouseover="window.status=\'afficher la page '+
google_ads[0].visible_url+'\';return true" target="_blank"><img border="0" src="'+
google_ads[0].image_url+'"width="'+
google_ads[0].image_width+'"height="'+
google_ads[0].image_height+'"></a>';}else if(google_ads[0].type=="html"){s+=google_ads[0].snippet;}else{s+='<a href=\"'+google_info.feedback_url+'\" class="ftGoogle" target="_blank">'+google_ad_title+'</a>'
for(i=0;i<google_ads.length;++i){s+='<div class="marT15"><h2><a class="floatRight ftWebsite" href="'+
google_ads[i].url+'" onmouseout="window.status=\'\'" onmouseover="window.status=\''+
google_ads[i].visible_url+'\';return true" target="_blank">'+
google_ads[i].visible_url+'</a><a href="'+
google_ads[i].url+'" onmouseout="window.status=\'\'" onmouseover="window.status=\''+
google_ads[i].visible_url+'\';return true" target="_blank">'+
google_ads[i].line1+'</a></h2> <p>'+
google_ads[i].line2+' '+
google_ads[i].line3+'</p> </div>';if(google_ads[0].bidtype=="CPC"){google_adnum=google_adnum+google_ads.length;}}}
document.write(s);return;}
gg_afs_query='';function google_afs_request_done(google_ads){var google_num_ads=google_ads.length;if(google_num_ads<=0){return;}
var google_ad_title='Google Ads';switch(ccm_language){case'fr':google_ad_title='Annonces Google';break;case'en':google_ad_title='Google Ads';break;case'es':google_ad_title='Anuncios Google';break;case'pt':google_ad_title='Anúncios Google';break;case'it':google_ad_title='Annunci Google';break;case'de':google_ad_title='Google-Anzeigen';break;}
var wideAds="";var narrowAds="";for(i=0;i<google_num_ads;i++){if(google_ads[i].type=="text/wide"){wideAds+='<div class="section"';wideAds+=' onmouseover="window.status=\''+google_ads[i].visible_url+'\'" onmouseout="window.status=\'\'" style="padding-top:15px"><div class="article">';wideAds+='<h2><a href="'+google_ads[i].url+'" onclick="PutThat(\''+google_ads[i].url+'\');return false;" style="color:rgb(20, 91, 201);font-weight:normal;text-decoration:underline">'+google_ads[i].line1+'</a></h2>';wideAds+='<p>'+google_ads[i].line2+'</p></div>';wideAds+='<div><a href='+google_ads[i].url+'"" style="color:#009900;" onclick="PutThat(\''+google_ads[i].url+'\');return false;">'+google_ads[i].visible_url+'</a></div>';wideAds+='</div>';}else{narrowAds+='<div class="section"';narrowAds+=' onmouseover="window.status=\''+google_ads[i].visible_url+'\'" onmouseout="window.status=\'\'" style="padding-top:15px"><div class="article">';narrowAds+='<h2><a href="'+google_ads[i].url+'" onclick="PutThat(\''+google_ads[i].url+'\');return false;" style="color:rgb(20, 91, 201);font-weight:normal;text-decoration:underline">'+google_ads[i].line1+'</a></h2>';narrowAds+='<p>'+google_ads[i].line2+'&nbsp;'+google_ads[i].line3+'</p></div>';narrowAds+='<div><a href="'+google_ads[i].url+'" style="color:#009900;" onclick="PutThat(\''+google_ads[i].url+'\');return false;">'+google_ads[i].visible_url+'</a></div>';narrowAds+='</div>';}}
feedbck='<a href="https://www.google.com/adsense/support/bin/request.py?contact=afs_violation" target="_blank" style="color:#898994;">'+google_ad_title+'</a><div class="clear"></div>';feedsmall='<a href="https://www.google.com/adsense/support/bin/request.py?contact=afs_violation" target="_blank" style="color:#898994;">'+google_ad_title+'</a><div class="clear"></div>';if(narrowAds!=""){narrowAds=feedbck+narrowAds;$('narrow_ads_unit').innerHTML=narrowAds;$('narrow_ads_unit').style.background='#F3FAFF';}
if(wideAds!=""){wideAds=feedsmall+wideAds;$('wide_ads_unit').innerHTML=wideAds;$('wide_ads_unit').style.background='#F3FAFF';}};mmenu={timer:0,select:function(cur_el,def){def=def||false;var elts=$("mmenu_ul_id").childNodes;for(var i=0;i<elts.length;i++){var elt=elts[i];if((elt===null)||(elt.nodeName.toLowerCase()!=='li')){continue;}
var is_cur=(elt.className.search(/current/)>=0);if(cur_el&&elt===cur_el){elt.className=(is_cur)?'selected current':'selected';}else{elt.className=(is_cur)?(def?'selected current':'current'):'';}}},tempo:function(){if(mmenu.timer){clearTimeout(mmenu.timer);}
mmenu.timer=setTimeout("mmenu.select(null, true)",2000);}};hputils={slideshow:{mod_img:function(cur_el,css_class){var _sl=$('slideshow');_sl.className=_sl.className.replace(/\s[^\s]+$/,' '+css_class);var _els=_sl.getElementsByTagName('a');for(var i=0;i<_els.length;i++){var _el=_els[i];if((_el===null)||(_el.id===null)||(_el.className==='button btColorTheme overlayW btMedium')){continue;}
_el.className=(cur_el&&_el===cur_el)?'selected':'';}}}};ccmu={dom:{add_class:function(el,style){el.className=el.className.replace(new RegExp('((\\s+|^)'+style+'(\\s+|$)|$)','i'),' '+style+' ').replace(/^\s+|\s+$/g,'').replace(/\s+/,' ');},remove_class:function(el,style){el.className=el.className.replace(new RegExp('(\\s+|^)'+style+'(\\s+|$)','i'),'').replace(/^\s+|\s+$/g,'').replace(/\s+/,' ');},loaded_css:{},css_include:function(css,media,id)
{id=id||css;if(ccmu.dom.loaded_css[id]){return true;}
try{var _css=document.createElement('link');_css.rel='stylesheet';_css.href=css;_css.type='text/css';_css.setAttribute('ccmskin',id);if(media){_css.media=media;}
var head=document.getElementsByTagName('head').item(0);head.appendChild(_css);ccmu.dom.loaded_css[id]=css;}catch(e){if(ccmu.dbg){ccmu.dbg('Erreur css_include '+css+': '+e);}
return e;}
return true;},remove_all_ccmcss:function(key){var _els=document.getElementsByTagName('link');for(var i=_els.length-1;i>=0;i--){var _ccmid=_els[i].getAttribute('ccmskin');if(_els[i].getAttribute('href')!==null&&_ccmid!==null){if(!key||_ccmid===key){delete ccmu.dom.loaded_css[_ccmid];_els[i].parentNode.removeChild(_els[i]);}}}}},evt:{get_event_infos:function(event){var _tgt=event.target||event.srcElement,_actid;if(_tgt){_actid=_tgt.getAttribute('actid')||false;if(!_actid&&_tgt.tagName.toLowerCase()==='img'&&_tgt.parentNode&&_tgt.parentNode.getAttribute('actid')){_tgt=_tgt.parentNode;_actid=_tgt.getAttribute('actid')||false;}}
return[_tgt,_actid];},stop_event:function(event){if(event.stopPropagation){event.stopPropagation();}else{event.cancelBubble=true;}
ccmu.evt.cancel_event(event);},cancel_event:function(event){if(event.preventDefault){event.preventDefault();}else{event.returnValue=false;}},_odr:{observers:[],done:false,timer:null},on_dom_ready:function(fct){var ie=!!(window.attachEvent&&!window.opera),webkit=navigator.userAgent.indexOf('AppleWebKit/')>-1,_o=ccmu.evt._odr.observers;if(ccmu.evt._odr.done){return fct();}
_o.push(fct);if(ccmu.evt._odr.callback){return;}
ccmu.evt._odr.callback=function(){if(ccmu.evt._odr.done){return;}
ccmu.evt._odr.done=true;if(ccmu.evt._odr.timer){clearInterval(ccmu.evt._odr.timer);ccmu.evt._odr.timer=null;}
var _o=ccmu.evt._odr.observers;for(var i=0,l=_o.length;i<l;i++){var fn=_o[i];_o[i]=null;fn();}
ccmu.evt._odr.observers=ccmu.evt._odr.callback=null;}
if(document.readyState&&webkit){ccmu.evt._odr.timer=setInterval(function(){var state=document.readyState;if(state=='loaded'||state=='complete'){ccmu.evt._odr.callback();}},10);}
else if(document.readyState&&ie){ccmu.evt._odr.timer=setInterval(function(){try{document.documentElement.doScroll('left');ccmu.evt._odr.callback();}catch(e){}},10);}else{if(document.addEventListener){document.addEventListener("DOMContentLoaded",ccmu.evt._odr.callback,false);}else if(window.attachEvent){window.attachEvent('onload',ccmu.evt._odr.callback);}else{var fn=window.onload;window.onload=function(){ccmu.evt._odr.callback();if(fn){fn();}};}}},_get_type:function(type){var _ie=(window.attachEvent);switch(type){case'focus':return(_ie)?'focusin':'focus';case'blur':return(_ie)?'focusout':'blur';default:return type;}},on:function(el,type,cb,obj,scope){var _capture=((type=='focus'||type=='blur')&&window.addEventListener)?true:false;var context=el;if(scope){context=(scope===true)?obj:scope;}
var _cb=function(event){if(cb.call(context,event||window.event,obj)===false){ccmu.evt.stop_event(event||window.event);}}
var _type=ccmu.evt._get_type(type);if(window.addEventListener){el.addEventListener(_type,_cb,(_capture));}else if(window.attachEvent){el.attachEvent("on"+_type,_cb);}else{return false;}
return true;},off:function(el,type,cb,obj,scope){var _capture=((type=='focus'||type=='blur')&&window.addEventListener)?true:false;var context=el;if(scope){context=(scope===true)?obj:scope;}
var _cb=function(event){return cb.call(context,event||window.event,obj);};var _type=ccmu.evt._get_type(type);if(window.removeEventListener){el.removeEventListener(_type,_cb,(_capture));}else if(window.detachEvent){el.detachEvent("on"+_type,_cb);}else{return false;}
return true;}},frm:{frm2qs:function(frm){var _aqs=[],_ori=false;frm=$(frm);for(i=0;i<frm.elements.length;i++){var _el=frm.elements[i];switch(_el.tagName.toLowerCase()){case"input":switch(_el.type){case"text":case"hidden":case"file":case'password':_ori=ccmu.frm._get_ori_attr(_el);_aqs.push(_el.name+"="+((!_ori||(_el.value!==_ori))?encodeURIComponent(_el.value):''));break;case"checkbox":if(_el.checked){_aqs.push(_el.name+"="+_el.value);}else{_aqs.push(_el.name+"=0");}
break;case"radio":if(_el.checked){_aqs.push(_el.name+"="+_el.value);}
break;}
break;case"textarea":_ori=_el.getAttribute('_ori')||false;_aqs.push(_el.name+"="+((!_ori||(_el.value!==_ori))?encodeURIComponent(_el.value):''));break;case"select":_aqs.push(_el.name+"="+_el.options[_el.selectedIndex].value);break;}}
return _aqs.join('&');},treecat_chk:function(){var _ret=true;if(this.elts.opts_form&&this.elts.opts_form.addcat&&this.elts.opts_form.addcat.value&&this.config.addconfmsg){_ret=confirm(this.config.addconfmsg);}
if(this.elts.opts_form&&this.elts.opts_form.movetocat&&(this.elts.opts_form.movetocat.value>=0)&&this.config.moveconfmsg){_ret=confirm(this.config.moveconfmsg);}
if(this.elts.opts_form&&this.elts.opts_form.deletecat&&this.elts.opts_form.deletecat.checked&&this.config.deleteconfmsg){_ret=confirm(this.config.deleteconfmsg);}
return _ret;},_get_ori_attr:function(_tgt){if(typeof _tgt.value=='string'){var _actid=_tgt.getAttribute('actid')||null,_ori=_tgt.getAttribute('_ori')||null;if((_ori===null)&&(_actid==='ofempty')){_ori=_tgt.value;_tgt.setAttribute('_ori',_tgt.value);}}
return _ori;}}}
ccmboxes={boxes:{}};ccmboxes.box=function(container,elts,config)
{this.container=$(container);if(this.container){this.id=this.container.id;}
this.config=config||{};elts=elts||{};if(elts.options&&(elts.options=='_auto_modale_')){this._opt_auto_modal=true;elts.options=document.body.insertBefore(document.createElement('div'),document.body.firstChild);elts.options.className='modale';elts.options.style.display='none';var _self=this;elts.options.onclick=function(event){event=event||window.event;return _self.on_click.call(_self,event);};}
this.elts={options:(elts.options)?$(elts.options):null,content:(elts.content)?$(elts.content):null};if(this.config.xhrprm){this.config.xhrprm+='&';}else{this.config.xhrprm='';}
this.create_events();if(this.config.reload){this.reload();}};ccmboxes.box.prototype={container:null,config:null,id:null,elts:null,_opt_auto_modal:false,toString:function(){return(' ccmbox id='+this.id);},create_events:function(){var _self=this;this.container.onclick=function(event){return _self.on_click.call(_self,event||window.event);};if(this.config.with_omo){var _el=$(this.config.with_omo);if(_el){$(this.config.with_omo).onmouseover=function(event){return _self.on_mouse_over.call(_self,event||window.event);};}}},on_click:function(event){var _tgt=event.target||event.srcElement,_actid=_tgt.getAttribute('actid')||false,_ret=false;if(!_actid){_tgt=_tgt.parentNode;_actid=_tgt.getAttribute('actid')||false;}
switch(_actid){default:_ret=true;break;case'optlink':_ret=this.toggle_opt();break;case'hidelink':if(this.elts.content.style.display==='none'){this.elts.content.style.display='block';_tgt.getElementsByTagName('span')[0].className='arrowDown';}else{this.elts.content.style.display='none';_tgt.getElementsByTagName('span')[0].className='arrowUp';}
break;case'delmyi':var _delid=_tgt.getAttribute('delid')||0;if(_delid&&(!this.config.msgdel||confirm(this.config.msgdel))){new Ajax.Updater(this.elts.content,this.config.url,{method:'get',parameters:this.config.xhrprm+'mode=remove&delid='+parseInt(_delid,10)});}
break;case'loadoptbynum':var _numact=_tgt.getAttribute('numact')||0;this.load_opt_frm('numact='+_numact+'&');break;}
return _ret;},on_submit:function(event)
{var _tgt=event.target||event.srcElement,_actid=_tgt.getAttribute('actid')||false,_ret=false;switch(_actid){default:break;case'optform':this.elts.opts_form=_tgt;if(this.config.withfile){var _sepa=(this.config.url.match(/\?/))?'&':'?',_self=this;this.elts.opts_form.action=this.config.url+_sepa+this.config.xhrprm+'mode=valid_opt';_ret=ajax_upload.submit(_self.elts.opts_form,{'onComplete':function(responseText){_self.callback_on_complete_upload.call(_self,responseText);}});}
else{_ret=this.submit_options_form();}
break;}
return _ret;},on_mouse_over:function(event)
{var _tgt=event.target||event.srcElement,_actid=_tgt.getAttribute('actid')||false,_ret=false;switch(_actid){default:break;case'slide':var _els=this.elts.content.getElementsByTagName('div'),_num=_tgt.getAttribute('num')||0,_tgts=_tgt.parentNode.parentNode.getElementsByTagName(_tgt.tagName),_curind=0;for(var i=0;i<_els.length;i++){var _inum=_els[i].getAttribute('num')||-1;if(_inum>=0){if(_inum==_num){_els[i].className=_els[i].className.replace(/\s?hide/,'');if(_tgts[_curind].className.search(/\s?selected/)===-1){_tgts[_curind].className+=' selected';}}else{if(_els[i].className.search(/\s?hide/)===-1){_els[i].className+=' hide';}
_tgts[_curind].className=_tgts[_curind].className.replace(/\s?selected/,'');}
_curind++;}}
break;}
return _ret;},toggle_opt:function(){if(!this.elts.options){return false;}
var _opt_el=this.elts.options;if(_opt_el.style.display==='none'){_opt_el.style.display='block';this.load_opt_frm();}else{_opt_el.style.display='none';}
return false;},load_opt_frm:function(more_prm)
{var _opt_el=this.elts.options,_self=this;more_prm=more_prm||'';new Ajax.Updater(_opt_el,this.config.url,{method:'post',parameters:this.config.xhrprm+more_prm+'mode=opt',onComplete:_self.set_options_form.call(_self),evalScripts:false});},reload:function(){if(this.elts.content){new Ajax.Updater(this.elts.content,this.config.url,{method:'get',parameters:this.config.xhrprm+'mode=content',evalScripts:false});}
return false;},set_options_form:function(){if(this.elts.options){var _self=this;setTimeout(function(){_self.elts.opts_form=_self.elts.options.getElementsByTagName('form')[0];if(_self.elts.opts_form){_self.elts.opts_form.onsubmit=function(event){event=event||window.event;return _self.on_submit.call(_self,event);}}},300);}},submit_options_form:function(){if(this.config.callback_frm_check){var _ok=this.config.callback_frm_check.call(this);if(!_ok){return false;}}
new Ajax.Updater(this.elts.content,this.config.url,{method:'post',parameters:this.config.xhrprm+'mode=valid_opt&'+ccmu.frm.frm2qs(this.elts.opts_form),evalScripts:false});this.toggle_opt();return false;},callback_on_complete_upload:function(responseText)
{this.elts.content.innerHTML=responseText;this.toggle_opt();}};ccmboxes.frm=function(container,elts,config,msg)
{this.container=$(container);if(this.container){this.id=this.container.id;}else{return false;}
this.config=config||{};elts=elts||{};if(elts.frm){switch(elts.frm){case'_auto_':this.elts.frm=this.container.getElementsByTagName('form')[0];break;default:this.elts.frm=$(elts.frm);break;}}
if(this.elts.frm&&elts.textarea){switch(elts.textarea){case'_auto_':this.elts.textarea=this.elts.frm.getElementsByTagName('textarea')[0];break;default:this.elts.textarea=$(elts.textarea);break;}}
this.elts.ajaxmsg=(elts.ajaxmsg)?$(elts.ajaxmsg):null;this.elts.divcpt=(elts.divcpt)?elts.divcpt:null;this.msg=msg||{};if(this.config.xhrprm){this.config.xhrprm+='&';}else{this.config.xhrprm='';}
this.create_events();return true;};articlesutils={activate_tab:function(el){var _cur_tab=el.parentNode;for(var _i in articlesutils.config.tabs){var _tab=$(articlesutils.config.tabs[_i][0])||null,_ctn=$(articlesutils.config.tabs[_i][1])||null;if(!_tab||!_ctn){continue;}
if(_tab===_cur_tab){_ctn.style.display='block';_tab.className='selected';}else{_ctn.style.display='none';_tab.className='';}}},elts:{},config:{},msg:{},init_edt_mode:function(prms,msg){articlesutils.elts={options:$('article_edit_opt'),content:$('article_cnt'),opts_form:null}
articlesutils.config=prms||{};articlesutils.msg=msg||{};if($('lnk_edit_article')){$('lnk_edit_article').onclick=function(){return articlesutils.toggle_opt('edit');}}
if($('lnk_add_article')){$('lnk_add_article').onclick=function(){return articlesutils.toggle_opt('add');}}
if($('lnk_add_sepa')){$('lnk_add_sepa').onclick=function(){return articlesutils.toggle_opt('addsepa');}}
articlesutils.elts.options.onclick=function(event){return articlesutils.on_click_form.call(articlesutils,event||window.event);};magiclink.num_btns_in_ul=1;},toggle_opt:function(act){if(!articlesutils.elts.options){return false;}
var _opt_el=articlesutils.elts.options;articlesutils.config.cur_act=act;if(_opt_el.style.display==='none'){_opt_el.innerHTML='';_opt_el.style.display='block';if(act=='edit'||act=='add'){if($('lnk_edit_article')){$('lnk_edit_article').style.display='none';}
if($('lnk_add_article')){$('lnk_add_article').style.display='none';}}
var _prm='';for(var _i in articlesutils.config){if((typeof _i==='string')&&(_i!=='url')&&(typeof articlesutils.config[_i]==='string')){_prm+='&'+_i+'='+articlesutils.config[_i];}}
new Ajax.Updater(_opt_el,articlesutils.config.url,{method:'post',parameters:'act='+act+_prm,evalScripts:true});}else{_opt_el.style.display='none';if(act=='edit'||act=='add'){if($('lnk_edit_article')){$('lnk_edit_article').style.display='block';}
if($('lnk_add_article')){$('lnk_add_article').style.display='block';}}}
return false;},toogle_preview:function(){if(!articlesutils.elts.opts_form){return false;}
var _f=$('frm_art_fields'),_pr=$('artpreview'),_su=articlesutils.elts.opts_form.artsubmit,_be=articlesutils.elts.opts_form.backtoedit,_ur=$('frm_edit_url');if(_f.style.display==='none'){_f.style.display='block';_be.style.display='none';if(_pr){_pr.style.display='inline';}
if(_ur){_ur.style.display='block';}
articlesutils.show_msg('','');}else{_f.style.display='none';_be.style.display='inline';if(_pr){_pr.style.display='none';}}
if(_su&&_be){_su.style.display=_be.style.display;}},set_options_form:function(){if(!articlesutils.elts.options){return false;}
articlesutils.elts.opts_form=articlesutils.elts.options.getElementsByTagName('form')[0];if(articlesutils.elts.opts_form){articlesutils.elts.opts_form.onsubmit=function(event){return articlesutils.on_submit.call(articlesutils,event||window.event);};articlesutils.elts.opts_form.onmouseover=function(event){return articlesutils.on_mover_form.call(articlesutils,event||window.event);};articlesutils.elts.opts_form.onmouseout=function(event){return articlesutils.on_mout_form.call(articlesutils,event||window.event);};articlesutils.elts.textarea=articlesutils.elts.opts_form.getElementsByTagName('textarea')[0];if(articlesutils.elts.textarea){articlesutils.elts.textarea.onfocus=function(event){document.onkeyup=magiclink.on_keyup;return true;};articlesutils.elts.textarea.onblur=function(event){document.onkeyup=null;return true;};articlesutils.elts.textarea.onclick=function(event){magiclink.on_click();return true;};if(articlesutils.elts.opts_form.act.value==='add'){$('art_title').innerHTML='...';articlesutils.elts.content.innerHTML='...';}}
document.getElementById('artpreview').disabled=false;}},on_submit:function(event){articlesutils.submit_option_form();},submit_option_form:function(){document.location='#topedit';articlesutils.show_msg(articlesutils.msg.start_upload,'boxInfos');articlesutils.show_overlay();new Ajax.Request(articlesutils.config.url,{method:'post',parameters:ccmu.frm.frm2qs(articlesutils.elts.opts_form),evalScripts:false,onSuccess:function(transport){articlesutils.hide_overlay();switch(articlesutils.elts.opts_form.mode.value){case'artpreview':articlesutils._after_submit(transport);break;case'artsubmit':articlesutils._after_submit(transport);if($('artsubmit')){$('artsubmit').style.display='none';}
if($('artclose')){$('artclose').style.display='';}
break;}},onFailure:function(transport){articlesutils.hide_overlay();switch(articlesutils.elts.opts_form.mode.value){case'artpreview':case'artsubmit':try{var _a=eval("("+transport.responseText+")");_a.msg=_a.msg||articlesutils.msg.ok_upload;articlesutils.show_msg(_a.msg,'boxError');}catch(e){articlesutils.show_msg(articlesutils.msg.error,'boxError');}
break;}}});return false;},_after_submit:function(transport)
{try{var _a=eval("("+transport.responseText+")");_a.msg=_a.msg||articlesutils.msg.ok_upload;if(_a.res){if(_a.title){$('art_title').innerHTML=_a.title;}
if(_a.content){articlesutils.elts.content.innerHTML=_a.content;}
articlesutils.show_msg(_a.msg,'boxValid');if(articlesutils.elts.opts_form.titletoc){articlesutils.elts.opts_form.titletoc.value=_a.titletoc;}
if(articlesutils.elts.opts_form.url){articlesutils.elts.opts_form.url.value=_a.url;}
if(_a.id&&articlesutils.elts.opts_form.ID){articlesutils.elts.opts_form.ID.value=_a.id;articlesutils.elts.opts_form.act.value='edit';}
if($('toc_ctn')&&_a.toc){$('toc_ctn').innerHTML=_a.toc;}}else{articlesutils.show_msg(_a.msg,'boxError');}}catch(e){articlesutils.show_msg(articlesutils.msg.error,'boxError');}},show_overlay:function()
{if($('overlay')){$('overlay').style.display='';}
setTimeout(function(){if($('cancel_request')){$('cancel_request').style.display='';}},5);},hide_overlay:function()
{if($('overlay')){$('overlay').style.display='none';}},on_click_form:function(event){var _tgt=event.target||event.srcElement,_actid=_tgt.getAttribute('actid')||false,_ret=false;if(!_actid){_tgt=_tgt.parentNode;_actid=_tgt.getAttribute('actid')||false;}
switch(_actid){default:_ret=true;break;case'optlink':_ret=articlesutils.toggle_opt(articlesutils.config.cur_act);break;case'textfmt':var _acttype=_tgt.getAttribute('acttype')||false;insertTag(articlesutils.elts.textarea,_acttype,true);break;case'mlcancelall':magiclink.cancel_all();break;case'mlapplyall':magiclink.apply_all();break;case'loadimgart':articlesutils.elts.opts_form.action=articlesutils.config.url;articlesutils.elts.opts_form.mode.value='loadimgart';_ret=ajax_upload.submit(articlesutils.elts.opts_form,{'onStart':articlesutils.callback_start_upload,'onComplete':articlesutils.callback_on_complete_upload});if(_ret){articlesutils.elts.opts_form.submit();}
_ret=false;break;case'artpreview':articlesutils.toogle_preview();articlesutils.elts.opts_form.mode.value='artpreview';articlesutils.submit_option_form();break;case'tooglepreview':articlesutils.toogle_preview();break;case'artsubmit':if($('frm_art_fields').style.display!=='none'){articlesutils.toogle_preview();}
articlesutils.elts.opts_form.mode.value='artsubmit';articlesutils.submit_option_form();break;}
return _ret;},callback_start_upload:function(){articlesutils.show_msg(articlesutils.msg.start_upload,'boxInfos');return true;},callback_on_complete_upload:function(responseText){try{var _a=eval(responseText);if(_a[0]===true){articlesutils.show_msg(articlesutils.msg.ok_upload,'boxValid');insertTag(articlesutils.elts.textarea,_a[1],false,true);}else{articlesutils.show_msg(_a[1],'boxError');}}catch(e){articlesutils.show_msg(articlesutils.msg.error,'boxError');}},on_mover_form:function(event){var _tgt=event.target||event.srcElement,_actid=_tgt.getAttribute('actid')||false,_ret=false;if(!_actid){_tgt=_tgt.parentNode;_actid=_tgt.getAttribute('actid')||false;}
switch(_actid){default:_ret=true;break;case'textfmt':var _actlbl=_tgt.getAttribute('actlbl')||false;BulleWrite(_actlbl);break;}
return _ret;},on_mout_form:function(event){var _tgt=event.target||event.srcElement,_actid=_tgt.getAttribute('actid')||false,_ret=false;if(!_actid){_tgt=_tgt.parentNode;_actid=_tgt.getAttribute('actid')||false;}
switch(_actid){default:_ret=true;break;case'textfmt':BulleHide();break;}
return _ret;},show_msg:function(msg,css){msg=msg||'';var _el=$('ajaxmsg');if(msg!==''){_el.style.display='block';css=css||'boxInfos';}else{_el.style.display='none';}
_el.className=css;_el.innerHTML=msg;}};ajax_upload={frame:function(c){var n='f'+Math.floor(Math.random()*99999);var d=document.createElement('DIV');d.innerHTML='<iframe style="display:none" src="about:blank" id="'+n+'" name="'+n+'" onload="ajax_upload.loaded(\''+n+'\')"></iframe>';document.body.appendChild(d);var i=document.getElementById(n);if(c&&typeof(c.onComplete)=='function'){i.onComplete=c.onComplete;}
return n;},form:function(f,name){f.setAttribute('target',name);},submit:function(f,c){ajax_upload.form(f,ajax_upload.frame(c));return(c&&typeof(c.onStart)=='function')?c.onStart():true;},loaded:function(id){var i=document.getElementById(id),d;if(i.contentDocument){d=i.contentDocument;}else if(i.contentWindow){d=i.contentWindow.document;}else{d=window.frames[id].document;}
if(d.location.href=="about:blank"){return;}
if(typeof(i.onComplete)=='function'){i.onComplete(d.body.innerHTML);}}}
ccmboxes.skin={css_url:'',css_ts:'',init:function(css_url,css_ts){this.css_url=css_url;this.css_ts=css_ts;},on_change:function(event){var _ret=false,_gei=ccmu.evt.get_event_infos(event),_tgt=_gei[0],_actid=_gei[1];if(_actid==='ofempty'){return true;}
switch(_actid){case'sel_skin':var _css=_tgt.value,_key=_tgt.id;if(_css<0){return false;}
new Ajax.Request('/xhr/save_prefs',{method:'get',parameters:'key='+_key+'&val='+_css,evalScripts:false,onSuccess:function(transport){if(transport.responseText==='ok'){ccmu.dom.remove_all_ccmcss(_key);if(!_css||_css==='ccm'){return false;}
_css=ccmboxes.skin.css_url.replace(/%s/,_css);_css+=((_css.search(/\?/)>=0)?'&amp;':'?')+ccmboxes.skin.css_ts;ccmu.dom.css_include(_css,'screen',_tgt.id);}else{alert(transport.responseText);}
return false;},onFailure:function(transport){alert(transport.responseText);}});break;default:return true;}
return _ret;}}